In [1]:
import numpy

print(help(numpy.genfromtxt))
# delimiter分隔符
# skip_header=1是否去掉第一行
# dtype=str指定数据类型
world_alcohol = numpy.genfromtxt("",dtype=str,skip_header=1,delimiter=',')

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [4]:
vector = numpy.array([5,10,15,20])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector)
print(matrix)

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [7]:
vector = numpy.array([1,2,3,4])
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])
print(vector.shape)
print(matrix.shape)

(4,)
(3, 3)


In [14]:
numbers = numpy.array([1,2,3,4.0])
print(numbers)
print(numbers.dtype)

[1. 2. 3. 4.]
float64


In [20]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
vector = numpy.array([1,2,3,4])
print(matrix[1,1])
print(vector[0:3])
print(matrix[0,0:3])
print(matrix[:,1])
print(matrix[:,0:2])
print(matrix[0:2,0:2])

25
[1 2 3]
[ 5 10 15]
[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[ 5 10]
 [20 25]]


In [24]:
vector = numpy.array([5,10,15,20])
# 判断数组里每一个数据是否等于十
vector == 10


array([False,  True, False, False])

In [25]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
matrix == 20

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [27]:
# true值返回，false直接过滤掉
vector = numpy.array([5,10,15,20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])

[False  True False False]
[10]


In [28]:
vector = numpy.array([5,10,15,20])
# 即等于十有等于五
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [30]:
vector = numpy.array([5,10,15,20])
# 即等于十或等于五
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)

[ True  True False False]


In [31]:
vector = numpy.array([5,10,15,20])
# 即等于十或等于五
equal_to_ten_or_five = (vector == 10) | (vector == 5)
print(equal_to_ten_or_five)
# 赋值
vector[equal_to_ten_or_five] = 50
print(vector)

[ True  True False False]
[50 50 15 20]


In [41]:
# 类型转化 astype
vector = numpy.array(["1","2","3","4"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)
vector = vector.astype(int)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3' '4']
float64
[1. 2. 3. 4.]
int32
[1 2 3 4]


In [44]:
# 求array数组的最大最小值以及和
vector = numpy.array([5,10,15,20])
vector_min = vector.min()
vector_max = vector.max()
vector_sum = vector.sum()
print(vector_min)
print(vector_max)
print(vector_sum)

5
20
50


In [51]:
matrix = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
# 按行求最小值
matrix_min = matrix.min(axis = 1)
print(matrix_min)
# 按列求最小值
matrix_min = matrix.min(axis = 0)
print(matrix_min)

[ 5 20 35]
[ 5 10 15]


In [57]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
a.shape

(3, 5)

In [60]:
# 查看矩阵维度
a.ndim

2

In [61]:
# 查看矩阵中数的个数
a.size

15

In [65]:
# 造数组
print(help(np.zeros))
np.zeros((3,4),int)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [66]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [67]:
# 类似for循环create数组
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [69]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
# 构建随机参数
np.random.random((2,3))

array([[0.11041483, 0.10929792, 0.03084836],
       [0.02048851, 0.11429859, 0.22576299]])

In [75]:
# 在起始值和终止值之间随机生成n个数作为数组
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [86]:
# 运算符操作(数组结构应该一样)
# 相当于对矩阵中的每一个数进行操作
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)
# 对应位置上的数相减,
c = a-b
print(c)
c = a - 1
print(c)
print(b**2)
print(a<35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 29 39 49]
[0 1 4 9]
[ True  True False False]


In [90]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
             [3,4]])
print(A)
print(B)
print(A*B)
# A对B进行矩阵操作
print(A.dot(B))
print(np.dot(A,B))

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [107]:
# 常用函数
B = np.arange(3)
# e的几次方
print(np.exp(B))
# 开方
print(np.sqrt(B))
# floor向下取整
a = np.floor(10*np.random.random((3,4)))
print(a)
print('-------------')
# 改变矩阵
print(a.ravel())
a.shape = (6,2)
print(a)
# 矩阵转置
print(a.T)

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[[6. 7. 4. 0.]
 [7. 0. 9. 8.]
 [1. 5. 7. 3.]]
-------------
[6. 7. 4. 0. 7. 0. 9. 8. 1. 5. 7. 3.]
[[6. 7.]
 [4. 0.]
 [7. 0.]
 [9. 8.]
 [1. 5.]
 [7. 3.]]
[[6. 4. 7. 9. 1. 7.]
 [7. 0. 0. 8. 5. 3.]]


In [110]:
# 矩阵拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)
# 行拼接
print(np.vstack((a,b)))
# 列拼接
print(np.hstack((a,b)))

[[4. 3.]
 [3. 2.]]
[[7. 0.]
 [7. 9.]]
[[4. 3.]
 [3. 2.]
 [7. 0.]
 [7. 9.]]
[[4. 3. 7. 0.]
 [3. 2. 7. 9.]]


In [117]:
# 切分矩阵
a = np.floor(10*np.random.random((2,12)))
print(a)
# 按列平均切分
print(np.hsplit(a,3))
# 指定列切分
print(np.hsplit(a,(3,4)))  # 从3位置切分，4位置切分
# 按行切分
a = np.floor(10*np.random.random((12,2)))
print(np.vsplit(a,3))

[[5. 0. 1. 0. 9. 7. 5. 0. 5. 8. 0. 7.]
 [9. 1. 8. 3. 9. 9. 5. 6. 3. 7. 4. 9.]]
[array([[5., 0., 1., 0.],
       [9., 1., 8., 3.]]), array([[9., 7., 5., 0.],
       [9., 9., 5., 6.]]), array([[5., 8., 0., 7.],
       [3., 7., 4., 9.]])]
[array([[5., 0., 1.],
       [9., 1., 8.]]), array([[0.],
       [3.]]), array([[9., 7., 5., 0., 5., 8., 0., 7.],
       [9., 9., 5., 6., 3., 7., 4., 9.]])]
[array([[8., 4.],
       [9., 4.],
       [4., 6.],
       [7., 3.]]), array([[1., 2.],
       [6., 9.],
       [7., 9.],
       [5., 3.]]), array([[4., 4.],
       [9., 0.],
       [1., 2.],
       [0., 5.]])]


In [126]:
# 赋值bug
a = np.arange(12)
b = a
a.shape = 3,4
# a = a.reshape(3,4)
print(a is b)
print(id(a))
print(id(b))

True
2588594257552
2588594257552


In [137]:
# 浅复制(数据还是共用)
c = a.view()
print(c)
print(c is a)
m = c == a
print(m.min())
c.shape = 2,6
c[0,4] = 1234
print(c.shape)
print(a.shape)
print(a)
print(id(a))
print(id(c))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
False
True
(2, 6)
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
2588594257552
2588594209296


In [141]:
d = a.copy()
print(d is a)
d[0,0] = 999
print(d)
print(a)

False
[[ 999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [151]:
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
# 返回最大值的索引值(列)
print(data.argmax(axis=0))
print(data[data.argmax(axis=0),range(data.shape[1])])
# 返回最小值的索引值(列)
print(data.argmin(axis=0))
print(data[data.argmin(axis=0),range(data.shape[1])])
print(range(data.shape[1]))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]
[1 4 4 2]
[-0.7568025  -0.96139749 -0.75098725 -0.99999021]
range(0, 4)


In [154]:
a = np.arange(0,40,10)
print(a)
# 行变原来的四倍，列变原来的两倍即行*4，列*2
b = np.tile(a,(4,2))
b

[ 0 10 20 30]


array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [159]:
# 排序
a = np.array([[4,3,5],[1,2,1]])
print(a)
# 按行排序
b = np.sort(a,axis = 1)
# b.sort(axis=1)
print(b)
# 按列排序
b = np.sort(a,axis = 0)
# b.sort(axis=0)
print(b)
# 按索引值排序（默认索引值）
a = np.array([4,3,1,2])
j = np.argsort(a)
print(j)
print(a[j])

[[4 3 5]
 [1 2 1]]
[[3 4 5]
 [1 1 2]]
[[1 2 1]
 [4 3 5]]
[2 3 1 0]
[1 2 3 4]
